#pragma once

// Do NOT forget to include the <iostream> here 
// because it's used in the prototypes of this .h file

#include <iostream>
using namespace std;

class rational
{
	
	int num, den;    // Numerator & Denominator

	          
	void fixSigns(); // fixSigns: Makes sure the Denominator is always non-negative. 
	                 // if it is negative, both the Numerator & Denominator are negated to fix this
	
	void removeGCD(); // removeGCD: Removes the greatest common divisor from the Numerator & Denominator. 
	                  // e.g. 2/2 => 1/1, 3/6 => 1/2

	int GCD(int a, int b); // GCD: Calculates the greatest common divisor for 2 numbers.

	// [Note]: we don't need the previous functions to be declared as public
	// because we will use it only inside the class (not OUTSIDE it to make it public)
	// Private member functions are called "Utility Function". Remember?

public:

	rational();       // initialize the rational to 0 (num 0, den 1)
	rational(int n);  // initialize the rational to n (num n, den 1)
	rational(int num, int den);
	~rational();

	int getNumerator() const;
	int getDenominator() const;

	// [Operators Overloaded as Members] ----------------------------------

	// Operators that do NOT change the calling object (left operand) 
	// --> can be "const" functions
	rational operator+ (const rational& other) const; // const function
	rational operator-(const rational& other) const;  // const function
	rational operator* (const rational& other) const; // const function
	rational operator/(const rational& other) const;  // const function

	//Prefix ++ & --
	rational operator++();
	rational operator--();

	//Postfix ++ & --
	rational operator++(int);
	rational operator--(int);

	rational operator-() const;

	rational operator+=(const rational& other);
	rational operator-=(const rational& other);
	rational operator*=(const rational& other);
	rational operator/=(const rational& other);

	bool operator==(const rational& other) const;
	bool operator!=(const rational& other) const;
	bool operator<(const rational& other) const;
	bool operator>(const rational& other) const;
	bool operator<=(const rational& other) const;
	bool operator>=(const rational& other) const;

	// [Operators Overloaded as Globals] ----------------------------------
	
	// Global operators are made friend for efficiency
	// They can be made as non-friend globals 
	// but you will need to call public getters and setters
	// and function calls have overhead as we mentioned before in the course
	// so, usually, the operators overloaded as global functions, declared as friend too for better performance.

	// Streaming operators to be used for input and output
	friend ostream& operator<<(ostream& output, const rational& number);
	friend istream& operator>>(istream& input, rational& number);

	friend rational operator+(int integer, const rational& number);
	friend rational operator-(int integer, const rational& number);
	friend rational operator*(int integer, const rational& number);
	friend rational operator/(int integer, const rational& number);

	friend bool operator==(int integer, const rational& number);
	friend bool operator!=(int integer, const rational& number);
	friend bool operator<(int integer, const rational& number);
	friend bool operator>(int integer, const rational& number);
	friend bool operator<=(int integer, const rational& number);
	friend bool operator>=(int integer, const rational& number);

	// [Important NOTE]: 

	// in the rational class you don't need to overload the = operator or the copy constructor
	// because the class doesn't have pointer data members that need deep copying
	// so, we can use the default assignment operator and default copy constructor
	// generated by the compiler (of the shallow copying; member-wise copying)
};


